### ISSUE TITLE
Add a path to a task

### ISSUE THREAD

**Issue by atanyday** [egslava/freemind-todo#1]
In big lists of topics everything works great. But it would be better to add titles to subtopics. For example I see lesson 2 in terminal "единицы измерения" but I can't remember to what topic it belongs.
![1](https://cloud.githubusercontent.com/assets/17011450/21564070/d6297738-ce99-11e6-8594-42f45d0161fa.jpg)

The same is with links. It's hard to remember where each link comes from. If it's possible, it would be great to see the title near each link.
![2](https://cloud.githubusercontent.com/assets/17011450/21564110/898686cc-ce9a-11e6-8ae0-48cbe40198e5.jpg)

**Comment by egslava** [comment]
Added to version 0.0.3. As usually, don't forget to update the package:
`sudo npm update -g freemind-todo`.

Now output looks like:
```
Viacheslavs-Air:freemind-todo egslava$ freemind-mm 
? There're your current tasks. Please, mark them after completion when you're done. (Press <space> to select, <a> to toggle all, <i> to inverse selection)
 ◯ English -> Grammar in Use -> Past Tenses -> Unit 4
 ◯ English -> Grammar in Use -> Future Tenses -> Unit 10 - Blah
 ◯ English -> Grammar in Use -> Adjectives and Adverbs -> Unit 91
 ◯ English -> Pronunciation
 ◯ English -> Australia Plus - Study English
❯◯ Web -> WordPress -> WordPress - Tutorial 4
 ◯ Web -> Angular -> JavaScript -> JS - Tutorial 3
 ◯ Web -> Angular -> Official Tutorials
 ◯ Web -> Angular -> Advanced lessons
```
