### ISSUE TITLE
TypeError: cannot read property

### ISSUE THREAD

**Issue by atanyday** [egslava/freemind-todo#2]
In a new version of app appears an error when I try to mark the task as done. 
And also one topic is displayed as undefined.
![1](https://cloud.githubusercontent.com/assets/17011450/21575866/a564cba4-cf2d-11e6-8ee8-89d84b3c7700.jpg)

When I add more topics, the error changes a little bit
![3](https://cloud.githubusercontent.com/assets/17011450/21575870/bf84dbdc-cf2d-11e6-8f1a-b0ba83423d6a.jpg)
[sosimple.mm.zip](https://github.com/egslava/freemind-todo/files/679480/sosimple.mm.zip)

**Comment by egslava** [comment]
@Annelia55 Hi! Thanks for your response.

I think I kind of 'can not reproduce' the error. I mean I can reproduce it with your file, but if I try to reduce file content to minimal - I can't do it. When I open and save the file - the error disappears.

What if you just resave file?

**Comment by Annelia55** [comment]
I tried to resave the file. It didn't help =(

**Comment by atanyday** [comment]
I resaved it, added new topics and subtopics. The error is the same. Take a look at my new file. 
![1](https://cloud.githubusercontent.com/assets/17011450/21582682/acc36508-d073-11e6-8d7a-d3f03f4ab0b8.jpg)
[sosimple.mm.zip](https://github.com/egslava/freemind-todo/files/680155/sosimple.mm.zip)

**Comment by egslava** [comment]
@Annelia55
What do you mean? I mean, can you reduce file content and send me to check? :-) When I try to do it - the error is fixing automatically. Perhaps, it’s due to FreeMind versions.

**Comment by egslava** [comment]
@Annelia55 could you please instead of adding something new, remove lots of content? :-)

**Comment by atanyday** [comment]
Of course. I deleted most of topics. Take a look
![2](https://cloud.githubusercontent.com/assets/17011450/21582697/1a99d5f8-d074-11e6-907b-407b8a1b4e5f.png)
[sosimple.mm.zip](https://github.com/egslava/freemind-todo/files/680156/sosimple.mm.zip)

**Comment by egslava** [comment]
@Annelia55 thanks for your report! I've tried to fix it.

Please, try update and run again: `npm update -g freemind-todo`

**Comment by atanyday** [comment]
The same error =(

**Comment by egslava** [comment]
@Annelia55 please, try update this way: `sudo npm install -g freemind-todo`

**Comment by egslava** [comment]
@Annelia55 by the way, which file doesn't work? The reduced one or the full one?

**Comment by egslava** [comment]
Thanks! :-) Finally, I've got the reason of the error. It seems, there's a bug in FreeMind - not all nodes have ID. So, sometimes, when FreeMind gives ID to everynode this bug is disappeared.

Now, I'm in progress of fixing it.

**Comment by egslava** [comment]
Fixed. Use: `sudo npm install -g freemind-todo`.
Tell me if something is wrong.

**Comment by atanyday** [comment]
Thanks a lot! Now it works ^_^
