### ISSUE TITLE
Hide Topic with done Subtopics in terminal

### ISSUE THREAD

**Issue by atanyday** [egslava/freemind-todo#3]
Is it possible to hide Topic in Terminal if all of its' subtopics are marked as done?
![1](https://cloud.githubusercontent.com/assets/17011450/21577004/f88c3c36-cf5a-11e6-8977-450b65209479.jpg)

**Comment by egslava** [comment]
It's possible, but I'm not sure that's necessary. I think it's a user decision what to do. It's easy - just to mark other one task as completed, but it's very awful if some tasks will be skipped if someone didn't expect such behaviour.

**Comment by atanyday** [comment]
Ok. Thanks for explanation.
